id: P010329
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN4684
  title: དེབ་ཐེར་དཀར་པོའི་ཟིན་བྲིས།
  author: ''
  volumes:
    05cdbdef8248461e84d81d485ef3ecc5:
      image_group_id: I3CN4686
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
