id: ICEC46DEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:43:33+00:00'
last_modified: '2022-06-08T12:47:24.388873+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4684
  title: དེབ་ཐེར་དཀར་པོའི་ཟིན་བྲིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2692':
      image_group_id: I3CN4686
      title: ''
      total_pages: 540
      order: 1
      base_file: 2692.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
